[project]
name = "borzoi"
version = "0.1.0"
description = "Start and stop runs."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyepics",
    "ess-streaming-data-types",
#    "ibex_non_ca_helpers"
]

[project.optional-dependencies]
dev = ["ruff"]
